import { i18n } from '@lingui/core';
import { getLocales } from 'expo-localization';
import { LanguageList } from './model/localize';

// Import messages - these will be generated by lingui compile
import { messages as enMessages } from './locales/en/messages';
import { messages as slMessages } from './locales/sl/messages';

const deviceLanguage = getLocales()[0]?.languageCode || LanguageList.EN;
const defaultLanguage = ['en', 'sl'].includes(deviceLanguage) ? deviceLanguage : LanguageList.EN;

// Load messages
i18n.load('en', enMessages);
i18n.load('sl', slMessages);

// Activate default language
i18n.activate(defaultLanguage);

export default i18n;
